name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write # Allows the workflow to push changes
  actions: read # Allows reading action logs
  pull-requests: write # Enables PR creation and updates

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create Laravel Project
        run: |
          composer create-project laravel/laravel laravel-test-project --no-interaction --no-progress
          mkdir -p laravel-test-project/packages/eren-laravel-commands

      - name: Copy Local Package
        run: rsync -av --exclude='laravel-test-project' ./ laravel-test-project/packages/eren-laravel-commands/

      - name: Link Local Package
        run: |
          composer config repositories.local '{"type": "path", "url": "packages/eren-laravel-commands", "options": {"symlink": true}}'
          composer require eren/laravel-commands:@dev --no-interaction --no-progress

      - name: Prepare Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear

      - name: Modify phpunit.xml to Include Package Tests
        run: |
          sed -i '/<\/testsuite>/i\        <directory suffix="Test.php">./packages/eren-laravel-commands/src/tests</directory>' phpunit.xml

      - name: Run Tests
        run: |
          php artisan test
