name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write # Allows the workflow to push changes
  actions: read # Allows reading action logs
  pull-requests: write # Enables PR creation and updates

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [9.*]  # Laravel versions to test
        php: [8.1, 8.2]  # PHP versions to test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Create Laravel ${{ matrix.laravel }}
        run: |
          composer create-project --prefer-dist laravel/laravel laravel-test-project "${{ matrix.laravel }}" --no-interaction
          mkdir -p laravel-test-project/packages/eren/laravel-commands

      - name: updating laravel
        working-directory: laravel-test-project
        run: |
          composer update laravel/framework

      - name: Laravel version
        run: composer show laravel/framework

      - name: Copy Local Package
        run: rsync -av --exclude='laravel-test-project' ./ laravel-test-project/packages/eren/laravel-commands/

      - name: Link Local Package
        working-directory: laravel-test-project
        run: |
          composer config repositories.local '{"type": "path", "url": "packages/eren/laravel-commands", "options": {"symlink": true}}'
          composer require eren/laravel-commands --no-interaction --no-progress

      - name: Prepare Laravel Environment
        working-directory: laravel-test-project
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear

      - name: Modify phpunit.xml to Include Package Tests
        run: |
          # sed -i '/<\/testsuite>/i\        <directory suffix="Test.php">packages/eren/laravel-commands/src/Tests</directory>' phpunit.xml
          rsync -av --exclude='laravel-test-project' ./src/Tests/ laravel-test-project/tests/Unit

      - name: Run Tests
        working-directory: laravel-test-project
        run: |
          php artisan test
